name: S3 Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # This can be changed, I just put this version somewhat arbitrarily

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm ci && rm -rf dist && npm run build

      - name: Replace localhost with production URL
        run: |
          find dist -type f -exec sed -i 's|http://localhost:8080|${{ secrets.BACKEND_SERVICE_URL }}|g' {} +

      - name: Create OIDC token to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.CI_IAM_ROLE }}
      - name: Push to AWS S3
        run: |
          aws s3 cp dist s3://${{ secrets.APP_BUCKET }} --recursive
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
